version: 0.{build}
branches:
  only:
  - master
configuration: Release
platform: x86
build:
  project: Mythology_Parade_Engine/Mythology_Parade_Solution.sln
  verbosity: minimal
after_build:
- cmd: >-
    copy C:\projects\Mythology-Parade\Mythology_Parade_Engine\Release\*.exe C:\projects\Mythology-Parade\Mythology_Parade_Engine\Game

    copy C:\projects\Mythology-Parade\README.md C:\projects\Mythology-Parade\Mythology_Parade_Engine\Game
artifacts:
- path: Mythology_Parade_Engine\Game
  name: Mythology-Parade
  type: WebDeployPackage
deploy:
- provider: GitHub
  release: Mythology Parade
  description: Mythology-Parade_V$(appveyor_build_version)
  auth_token:
    secure: KghY3L0nvYfR/6rGwcBUlM53HHU9raYtqIrE0BvIRnEH8zLvseMPPcA8inwVk5vT
  repository: projects/Misioneros-Studio/Mythology-Parade