version: 0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
skip_branch_with_pr: true
configuration: Release
shallow_clone: true
build:
  verbosity: minimal
after_build:
- cmd: >-
    copy C:\projects\Mythology-Parade\Mythology_Parade_Engine\Release\*.exe C:\projects\Mythology-Parade\Mythology_Parade_Engine\Game\

    copy C:\projects\Mythology-Parade\README.md C:\projects\Mythology-Parade\Mythology_Parade_Engine\Game\
artifacts:
- path: Mythology_Parade_Engine\Game
  name: Mythology-Parade
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: Mythology-Parade_V$$(appveyor_build_version)
  release: Mythologhy Parade v$(appveyor_build_version)
  description: Automatic Release
  auth_token:
    secure: 40a0e17514111084e5af9a7896421edaeb8e719b
notifications:
- provider: GitHubPullRequest
  template: Release Successful
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false