version: 0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
configuration: Release
platform: x86
shallow_clone: true
build:
  verbosity: minimal
after_build:
- cmd: >-
    copy C:\projects\mythology-parade\Mythology_Parade_Engine\Release\Mythology_Parade.exe  C:\projects\mythology-parade\Mythology_Parade_Engine\Game\


    copy  C:\projects\mythology-parade\Mythology_Parade_Engine\README.md  C:\projects\mythology-parade\Mythology_Parade_Engine\Game\
artifacts:
- path: Mythology_Parade_Engine\Game
  name: Mythology-Parade
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Mythology_Parade
  auth_token:
    secure: PSvYRm2n+XTf3FxysUnVKLaZJaOQbHqYCb0gbG8WPVJkazEzVmyErRbb3tZrrbAf